### ISSUE TITLE
Expression.Error: The column 'customerId' of the table wasn't found.

### ISSUE THREAD

**Issue by isaiahwilliams** [microsoft/secmgmt-insights-connector#137]
## Steps to reproduce

Perform the following tasks

1. Install the connector in customer environment 
2. Open Power BI Desktop
3. Click Get Data and then select the Security and Management Insights connector 
4. Click on the Users table

## Expected behavior

That the list of available users for the tenant would be loaded

## Actual behavior

```output
Expression.Error: The column 'customerId' of the table wasn't found.
```

## Diagnostic logs

N/A

## Environment

> Power BI Desktop
> Security and Management Insights connector version 2.1

**Comment by DeanGross** [comment]
I am getting this same error for many tables.
