### ISSUE TITLE
Error Install-SecMgmtInsightsConnector

### ISSUE THREAD

**Issue by shnax1** [microsoft/secmgmt-insights-connector#40]
Hi Isaiah
Get the following error trying to Install the application.
Also I want specify for it to go into a specific subscription. Can you provide relevant coding for that.
Would you be willing to arrange a one-on-one teams session to work through this with me? I am keen to see if this does what  I am hoping it does

Install-SecMgmtInsightsConnector -ApplicationDisplayName 'Security and Management Insights' -ConfigurePreconsent:$true
Install-SecMgmtInsightsConnector : Code: Request_UnsupportedQuery
Message: Unsupported Query.
Inner error:
	AdditionalData:
	date: 2020-07-10T03:51:13
	request-id: 1ad30bc8-e71a-4501-b8df-7aebc87c25a0
ClientRequestId: 1ad30bc8-e71a-4501-b8df-7aebc87c25a0
At line:1 char:1
+ Install-SecMgmtInsightsConnector -ApplicationDisplayName 'Security an ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Install-SecMgmtInsightsConnector], ServiceException
    + FullyQualifiedErrorId : Microsoft.Online.SecMgmt.PowerShell.Commands.InstallSecMgmtInsightsConnector

**Comment by isaiahwilliams** [comment]
@shnax1 thank you for reporting this issue. An updated version of the PowerShell module was just released that contains a fix for this issue. You can use the following to update to the latest version of the module 

```powershell
Update-Module SecMgmt
```

After you have installed the update, it is recommended that you close and reopen PowerShell before trying the operation again. That way you can be sure the updated version of the module is being used.

**Comment by shnax1** [comment]
Hi Isaiah
Thank you that resolved that issue.   I am not hugely proficient with all of this so following the step by step instructions. But what do I do after I have installed the connectors? What else needs to be configured and how in order to get the application to work?

**Comment by isaiahwilliams** [comment]
@shnax1 now that you have the connector installed you can utilize the functions it exposes in Power BI. To help with this discovery I have included a [template](https://github.com/microsoft/secmgmt-insights-connector/blob/master/templates/secmgmt-insights-partner-standard.pbit) for a Power BI report that can be opened using Power BI Desktop. As it relates to getting started guide, I am actually working through that right now. It should be published in the coming days. Once it is I will be sure to let you know.

**Comment by shnax1** [comment]
Thank Isaiah
I have opened the template in Desktop Power BI but am not getting the data pulled through.  See attached .  I will wait until you have the "how to " guide setup so as not to bug you each step of the way.   It really looks great!  Thank you
![BI](https://user-images.githubusercontent.com/62745322/87294408-0b660d80-c504-11ea-959f-c88c5076152d.png)

**Comment by isaiahwilliams** [comment]
@shnax1 thank you for sharing the above information. Based on the screenshot it looks like you are using the advanced template instead of the standard one. The primary difference between the two is the advanced includes Office 365 ATP information that is obtained form a connector named `SecMgmtInsights.PowerShell`. This connector requires an instance of Azure Functions to be deployed to turn the Exchange Online PowerShell, the source of the information, into an API that can be leveraged by Power BI. 

If you are encountering the same issues with this (template)[https://github.com/microsoft/secmgmt-insights-connector/blob/master/templates/secmgmt-insights-partner-standard.pbit) please let me know and I will get that resolved promptly.

**Comment by shnax1** [comment]
Hi Isaiahwilliams - thank you I have tried the Std template buts its been sitting on a refresh "waiting for other queries" screen for almost an hour .   I have killed Power BI and tried again but still the same.
![BI2](https://user-images.githubusercontent.com/62745322/87319586-1af84d00-c52a-11ea-8c78-ee1f8ee8110a.JPG)

**Comment by isaiahwilliams** [comment]
@shnax1 the documentation has been updated with how to get started. It is expected that the initial refresh will take some time because it is gathering data for all your customers. Let us know if you have any concerns or questions.
