### ISSUE TITLE
Cannot import templates

### ISSUE THREAD

**Issue by yurykissin** [microsoft/secmgmt-insights-connector#47]
# Steps to reproduce
Have run latest version of PS script to install the app on Azure, downloaded latest MEZ file and signed it with valid cert. When try to import the PowerBI template file its stuck on waiting for other queries for a very long time, then fails with error. same for both template files. 
When I create a new empty report, I can Get Data from the basic connector and see all tables are full with details so I guess the app is configured correctly. 
no matter how much I try creating a report from template, same error always.

## Expected behavior
would love to see a working PowerBI report using the template.

## Environment
CSP partner with lots of customers
Latest Win10, PowerBI desktop
![Screen Shot 2020-07-16 at 0 55 04](https://user-images.githubusercontent.com/25561453/87602076-04efb580-c6ff-11ea-8941-ccadc12cf015.png)

**Comment by isaiahwilliams** [comment]
@yurykissin by chance do you know what the error was?

**Comment by yurykissin** [comment]
@isaiahwilliams its just goes on and on for ever (my last try was more than an hour ago, its still running...)
i see that it takes a whole lot of memory also, its now on more than 5gb.
could it be cuz i have lots of customers?

**Comment by isaiahwilliams** [comment]
@yurykissin more than likely. The template will attempt to get data for all of your customers and import it. I have been making some improvements to address the refresh time and ultimately the issue you have encountered. The hope is to have this update available later this week. By chance would you mind sharing how many customers you have?

**Comment by yurykissin** [comment]
@isaiahwilliams about 500. 
im trying to run now on an empty (new) report. got data from the SecMgmt connector, all data is in but only for my own tenant. changed the query of Users table to 'Source = SecMgmtInsights.Users(GetTenantList())' 
GetTenantList function returns 494 rows, Users still running 'Waiting for SecMgmtInsights', from time to time I see amount of rows add keeps growing.
its been running for about 20min now, it loaded ~13k rows.

**Comment by isaiahwilliams** [comment]
@yurykissin thank you for sharing this information. With the current design the template will try to get everything for all customers. Given the number of customers you have it is expected for refreshing to take a bit of time. Part of this time is due to how the connector will attempt to retry failed requests. There are a number of enhancements under development in this area that should help reduce the amount of memory and time it takes to update everything. If you encounter errors with this version please let us know.

**Comment by yurykissin** [comment]
@isaiahwilliams thx for the update. looking forward for the new version.

**Comment by yurykissin** [comment]
@isaiahwilliams hi, if it help you at all, attached error. query been running for few hours, i saw the numbers go up but eventually failed.
![Screen Shot 2020-07-16 at 9 00 57](https://user-images.githubusercontent.com/25561453/87632918-09d65880-c743-11ea-9a89-d14416f0df4f.png)

**Comment by isaiahwilliams** [comment]
@yurykissin thank you for sharing this information. I just released version 1.2 that includes some of the performance updates I mentioned earlier. Through this release there was an update made to the connector and the standard partner template. Currently there is not an easy way to update the connector. Right now the best option is to walk back through the install process and follow the prompts that you will receive. Currently I am working on simplifying this process and hope to have a cmdlet in the PowerShell module for this process available by early next week.

**Comment by isaiahwilliams** [comment]
If you are still having issues with this please let us know, and we will be glad to help.
